# Generated by Django 4.1.3 on 2022-11-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='urls',
            new_name='Url',
        ),
    ]
